name: Deploy Dash App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        echo "$EC2_SSH_KEY" > key.pem
        chmod 600 key.pem
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/dash-app/

    - name: Create venv on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s' <<'EOF'
          cd ~/dash-app
          python3 -m venv venv
          . venv/bin/activate
          pip3 install -r requirements.txt
        EOF
